{% set name = "djangorestframework-dataclasses" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/djangorestframework-dataclasses-{{ version }}.tar.gz
  sha256: 4fa8d93a19a3e256487674e9c654b45992bc76de155bd097eced6fe4af4100a2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools >=61
    - wheel
    - pip
  run:
    - python >=3.7
    - django >=2.0
    - djangorestframework >=3.9
    - typing-extensions >=3.7.4

test:
  commands:
    - python -c "from django.conf import settings; settings.configure(DEBUG=True); from rest_framework_dataclasses.serializers import DataclassSerializer"  
    - pip check
  requires:
    - pip

about:
  home: https://github.com/oxan/djangorestframework-dataclasses
  summary: A dataclasses serializer for Django REST Framework
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
